### PR TITLE
Updating Cygnus TourGuide according to the guidelines

### PR DESCRIPTION
**Pull request by anmunoz**
Updating Cygnus TourGuide according to the guidelines @jmcanterafonseca @jason-fox

### CODE REVIEW

**Comment by jason-fox** [comment]
The `mkdocs.yml` is still referring to the deleted file:

```
 - 'Cygnus - Store Context Information': 'core/cygnus/how-to-store-data-cygnus-mysql.md'
```

Could you amend it please.

**Comment by anmunoz** [comment]
@jason-fox Thanks, now is updated

**Comment by jmcanterafonseca** [comment]
General Comment: I think Cygnus 1 and Cygnus 2 should live together until Cygnus 2 is complete estable and tested so I think the old Cygnus documentation should remain

**Comment by jason-fox** [comment]
@jmcanterafonseca  - I agree the old content is useful, but the old content was written as a **tutorial**, not a tour guide of features. 

The old content has been updated and ported to a separate [tutorial repo](https://github.com/Fiware/tutorials.Historic-Context)

**Pull request merged**
